// Generated by https://quicktype.io

export interface CompletedOrdersResponse {
    totalpaginas:    number;
    totalentregados: number;
    totalregistros:  string;
    listaentregados: CompletedListResponse[];
    versionConfig:   string;
    versionAPP:      string;
    tagManagerID:    string;
    tagManagerIDCS:  string;
    visibleMenuCV:   boolean;
}

export interface CompletedListResponse {
    nopedido:          string;
    estatus:           string;
    fechacolocacion:   string;
    fechaautorizacion: string;
    sku:               string;
    articulo:          string;
    fechaembarque:     string;
    mensajeria:        string;
    noguia:            string;
    estatusguia:       string;
    claroid:           string;
    idpedidorelacion:  string;
    totalproducto:     string;
    totalpedido:       string;
    skuhijo:           string;
    fulfillment:       boolean;
    channel:           string;
    transactionid:     number;
}
